# Generated by Django 3.2.13 on 2023-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='id',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='regNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
