# Generated by Django 3.2.13 on 2023-07-27 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_auto_20230725_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
