# Generated by Django 3.2.13 on 2023-08-06 18:54

import django.core.validators
from django.db import migrations, models
import feedbackapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_visitor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.PositiveIntegerField(validators=[feedbackapp.models.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='regNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_reg_num', message="Registration number must start with 'VU' or 'vu'", regex='^(VU|vu)\\w+$')]),
        ),
    ]
