# Generated by Django 3.2.13 on 2023-08-06 19:03

from django.db import migrations, models
import feedbackapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0004_auto_20230806_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='regNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[feedbackapp.models.validate_reg_num]),
        ),
    ]
