# Generated by Django 3.2.13 on 2023-08-06 19:08

from django.db import migrations, models
import feedbackapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0005_alter_visitor_regnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='regNum',
            field=models.CharField(max_length=20, validators=[feedbackapp.models.validate_reg_num]),
        ),
    ]
