# Generated by Django 3.2.13 on 2023-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0007_auto_20230806_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='regNum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
