# Generated by Django 4.1.7 on 2023-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbackapp", "0008_auto_20230807_0520"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visitor",
            name="regNum",
            field=models.CharField(max_length=20),
        ),
    ]
